In [1]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.describe(include='all')

sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [2]:
import numpy as np
iris_array = iris.iloc[:, :-1].to_numpy()
type(iris_array)

numpy.ndarray

In [3]:
iris_array.shape

(150, 4)

In [4]:
from scipy.stats import kurtosis, skew
# normal: 정규분포
# uniform: 균일분포
data = np.random.normal(0, 1, 10000000)

print(np.mean(data))
print(np.var(data))
print(np.std(data))
print(skew(data))
print(kurtosis(data))

-0.00026996917555028736
0.9997691953924287
0.9998845910365999
-0.0013003939389782339
0.0013360595676723541


### 인코딩 수행 예시

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
le.fit(iris.species)

LabelEncoder()

In [7]:
le.transform(iris.species[0:100])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
le.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
data = [0, 1, 1, 1, 0, 0, 2, 1, 2, 1, 2] # 이 값의 종 이름 출력
le.inverse_transform(data)

array(['setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica'], dtype=object)

In [10]:
le.classes_[data]

array(['setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica'], dtype=object)

In [11]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit(iris.species)
lb.transform(iris.species)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [12]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

enc.fit(iris.species.to_numpy().reshape(-1, 1))
iris_onehot = enc.transform(iris.species.to_numpy().reshape(-1, 1))
iris_onehot.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
import pandas as pd
pd.get_dummies(iris.species)

setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [14]:
from sklearn.model_selection import train_test_split
X = iris.iloc[:, :-1]
y = iris.species

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, stratify=y)

train_X.shape, test_X.shape, train_y.shape, test_y.shape

((105, 4), (45, 4), (105,), (45,))

In [15]:
train_y.value_counts()

versicolor    35
setosa        35
virginica     35
Name: species, dtype: int64