## 1절. 넘파이 패키지

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3, 5)

In [5]:
# 축의 수 aka 튜플의 길이 (차원)
a.ndim

2

In [8]:
a.dtype
a.dtype.name

'int32'

In [10]:
# 각 요소 바이트 단위 크기(int32이므로 4byte)
a.itemsize

4

In [12]:
# 배열 요소 전체 개수
a.size

15

In [17]:
b = np.arange(12, dtype=np.int32).reshape(3, 4)
b.dtype

dtype('int32')

In [15]:
# dtype은 각 요소의 타입 변경 안함
# 아래와 같이 강제로 바꿀 시 요소 값을 변경함 => 대참사
# b.dtype = np.int64
# b

array([[ 4294967296, 12884901890],
       [21474836484, 30064771078],
       [38654705672, 47244640266]], dtype=int64)

In [22]:
# astype으로 배열 요소 타입 변경
b_64 = b.astype(np.int64)
b_64
b_64.dtype

dtype('int64')

## 2절. 넘파이 배열

In [23]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [24]:
a.dtype

dtype('int32')

In [26]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [28]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [29]:
c = np.array([[1, 2], [3, 4]], dtype=np.float32)
c

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [32]:
# 기존 객체 이용한 새로운 배열 복사본 생성 안함
d = np.array(c, copy=False)
print(id(c), id(d))

e = np.array(c, copy=True)
print(id(c), id(e))

1898962664208 1898962664208
1898962664208 1898826229296


In [34]:
# copy=False 여도 dtype에 다른 유형 지정되면 복사본 생성됨.
d = np.array(c, copy=False, dtype=int)
print(id(c), id(d))

1898962664208 1898768924560


In [39]:
# 기본값이 있는 배열
x = np.zeros((3, 4))
x
x.dtype

dtype('float64')

In [40]:
np.ones((2, 3, 4), dtype=np.int64)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [42]:
# 현재 커널에 있는 쓰레기 데이터 값으로 채움
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [47]:
# 연속된 값 갖는 배열
print(np.arange(10))
print(np.arange(11, 20))
print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3))

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [49]:
print(np.linspace(0, 2, 9))
print(np.linspace(0, 10, 20))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [55]:
x = np.linspace(0, 2*np.pi, 10)
y = np.sin(x)
print(x, y)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531] [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [52]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# 차원이 풀린 배열 반환
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
# 전치행렬 transposed 반환
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
# reshape()는 차원 수정된 배열 반환
# resize()는 배열 자체 수정

a = np.arange(12).reshape(3, 4)
a.resize(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [63]:
# 크기 -1로 주어질 시, 해당 차원의 크기 자동으로 계산됨
# resize는 -1 사용못함
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [64]:
a.shape = (2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
# numpy가 요소 값 생략 안하고 전체 배열 인쇄하도록 설정
# threshold: threshold값이 배열의 데이터 수보다 크거나 같아야 전체 데이터 인쇄할 수 있음

np.set_printoptions(threshold=1000)
print(np.arange(100).reshape(10, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [67]:
# 배열 연산
a = np.array([20, 30, 40, 50])
b = np.arange(4)

a - b

array([20, 29, 38, 47])

In [68]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [70]:
a < 35

array([ True,  True, False, False])

In [74]:
a = np.array( [[1,1], [0,1]] )
b = np.array( [[2,0], [3,4]] )

# 요소별 곱
print(a * b)
# 행렬 곱
print(a.dot(b))
print(a@b)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [80]:
a = np.ones((2, 3), dtype=np.int32)
b = np.arange(6).reshape(2, 3).astype(np.float32)

print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0. 1. 2.]
 [3. 4. 5.]]


In [81]:
a *= 3
print(a)

b += a
b

[[3 3 3]
 [3 3 3]]


array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [84]:
# 배열 요소의 집계
a = np.arange(12).reshape(3, 4)
print(a)
a.sum(), a.min(), a.max(), a.mean(), a.std()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(66, 0, 11, 5.5, 3.452052529534663)

In [86]:
# 열이 같고 행 인덱스가 변하는 값들의 합 (열 별 합계)
print(a.sum(axis=0))

# 행이 같고 열 인덱스가 변하는 값들의 합 (행 별 합계)
print(a.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


In [87]:
A = np.arange(3) # array([0, 1, 2])
B = np.arange(4,7) # array([4, 5, 6])

# 범용함수
np.add(A, B)

array([4, 6, 8])

In [94]:
# 메모리 사용량 및 실행시간 비교
%load_ext memory_profiler

a = np.random.randn(100000000)
b = np.random.randn(100000000)
c = np.random.randn(100000000)

The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler


In [95]:
%%time # 셀을 실행시킨 시간 출력
%memit g = a + b + c # 해당 구문 실행할 때 메모리 사용량 출력
g

peak memory: 3673.80 MiB, increment: 1253.18 MiB
Wall time: 1.55 s


array([-2.34267143, -1.78434815,  2.33649324, ...,  1.73877098,
       -0.51954677,  3.08317729])

In [96]:
%%time
%memit T1 = a * b; G = T1 + c; del T1
print(G)

peak memory: 4700.59 MiB, increment: 1517.02 MiB
[-2.95168647 -1.16070155  1.4955757  ...  1.22045654 -0.66096671
  1.79736573]
Wall time: 1.55 s


In [97]:
%%time
%memit G = a * b; G += c
print(G)

peak memory: 4629.61 MiB, increment: 690.73 MiB
[-2.95168647 -1.16070155  1.4955757  ...  1.22045654 -0.66096671
  1.79736573]
Wall time: 1.37 s


In [98]:
%%time
%memit G = a * b; np.add(G, c, G)
print(G)

peak memory: 4609.95 MiB, increment: 671.07 MiB
[-2.95168647 -1.16070155  1.4955757  ...  1.22045654 -0.66096671
  1.79736573]
Wall time: 1.32 s


In [100]:
# 브로드캐스팅
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

print(a * b)
print(np.multiply(a, b))

[2 4 6]
[2 4 6]


In [101]:
a = np.array([1, 2, 3])
b = 2

a*b

array([2, 4, 6])

In [102]:
A = np.array([[ 0, 0, 0],
[10, 10, 10],
[20, 20, 20],
[30, 30, 30]])

B = np.array([1, 2, 3])

A + B

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [104]:
A = np.array([0.0, 10.0, 20.0, 30.0])
B = np.array([1.0, 2.0, 3.0])

A[:, np.newaxis] + B # A[:, np.newaxis]는 4*1 모양의 2차원 배열
# 행 또는 열의 차원 승격

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

## 3절. 배열 합치기/나누기

## 4절. 복사와 뷰

## 5절. 고급 인덱싱

## 6절. 선형대수학

## 7절. 유용한 정보 및 팁

## 8절. 연습문제